#spring.datasource.url=jdbc:mysql://localhost/friends
#spring.datasource.username=root
#spring.datasource.driver-class-name=com.mysql.jdbc.Driver
#spring.jpa.generate-ddl=true
#spring.jpa.show-sql=true

server.port: 8082

spring:
  datasource:         #isn't truly required for in-memory H2 Database, only added here for referece to configure different DB
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    show-sql: true


#  spring.datasource.url=jdbc:h2:mem:testdb
#  spring.datasource.driverClassName=org.h2.Driver
#  spring.datasource.username=sa
#  spring.datasource.password=password
#  spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#
#  spring.jpa.generate-ddl=true
#  spring.jpa.show-sql=true


#server.error.whitelabel.enabled=false